ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "scheduled_start_at" timestamp;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "scheduled_end_at" timestamp;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "late_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "late_return_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "early_departure_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "unapproved_overtime_minutes" integer NOT NULL DEFAULT 0;
ALTER TABLE "attendance_daily_records" ADD COLUMN IF NOT EXISTS "tolerance_status" varchar(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE "attendance_daily_records" ADD CONSTRAINT "chk_attendance_daily_record_late_minutes" CHECK ("late_minutes" >= 0);
ALTER TABLE "attendance_daily_records" ADD CONSTRAINT "chk_attendance_daily_record_late_return_minutes" CHECK ("late_return_minutes" >= 0);
ALTER TABLE "attendance_daily_records" ADD CONSTRAINT "chk_attendance_daily_record_early_departure_minutes" CHECK ("early_departure_minutes" >= 0);
ALTER TABLE "attendance_daily_records" ADD CONSTRAINT "chk_attendance_daily_record_unapproved_overtime_minutes" CHECK ("unapproved_overtime_minutes" >= 0);
ALTER TABLE "work_schedules" ADD COLUMN IF NOT EXISTS "schedule_type" varchar(40) NOT NULL DEFAULT 'WEEKLY';
ALTER TABLE "work_schedules" ADD COLUMN IF NOT EXISTS "roster_on_days" integer NOT NULL DEFAULT 1;
ALTER TABLE "work_schedules" ADD COLUMN IF NOT EXISTS "roster_off_days" integer NOT NULL DEFAULT 0;
ALTER TABLE "work_schedules" ADD CONSTRAINT "chk_work_schedule_type" CHECK ("schedule_type" IN ('WEEKLY', 'ROSTER'));
ALTER TABLE "work_schedules" ADD CONSTRAINT "chk_work_schedule_roster_on_days" CHECK ("roster_on_days" > 0);
ALTER TABLE "work_schedules" ADD CONSTRAINT "chk_work_schedule_roster_off_days" CHECK ("roster_off_days" >= 0);
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "arrangement_type" varchar(40) NOT NULL DEFAULT 'BIOMETRIC_EXEMPTION';
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "authorized_location" text;
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "effective_from" date;
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "effective_to" date;
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "review_due_at" date;
ALTER TABLE "biometric_exemptions" ADD COLUMN IF NOT EXISTS "responsible_authority" text;
ALTER TABLE "biometric_exemptions" ADD CONSTRAINT "chk_biometric_exemption_effective_dates" CHECK ("effective_to" IS NULL OR "effective_from" IS NULL OR "effective_from" <= "effective_to");
